# fly.toml file generated for change-product-name-shopify on 2022-11-09T19:52:03+09:00

app = "change-product-name-shopify"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8081"
  HOST = "https://change-product-name-shopify.fly.dev/"
  SHOPIFY_API_KEY = "c3aff4d0e05608216a274ec3fe82ee0d"
  SCOPES = "write_products"
[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8081
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
